schema: schema.docs.graphql
documents: '**/*.graphql'
extensions:
  endpoints:
    github:
      url: 'https://api.github.com/graphql'
      headers:
        Authorization: Bearer ${REACT_APP_GITHUB_ACCESS_TOKEN}
      introspect: false

